//
//  categories.swift
//  Yelp
//
//  Created by Hao Wang on 2/13/15.
//  Copyright (c) 2015 Timothy Lee. All rights reserved.
//

import Foundation
struct Categories {
    var categories:[Dictionary<String, String>]
    init() {
        categories = [["name" : "Afghan", "code": "afghani"]]
        categories += [["name" : "African", "code": "african"]]
        categories += [["name" : "American, New", "code": "newamerican"]]
        categories += [["name" : "American, Traditional", "code": "tradamerican"]]
        categories += [["name" : "Arabian", "code": "arabian"]]
        categories += [["name" : "Argentine", "code": "argentine"]]
        categories += [["name" : "Armenian", "code": "armenian"]]
        categories += [["name" : "Asian Fusion", "code": "asianfusion"]]
        categories += [["name" : "Asturian", "code": "asturian"]]
        categories += [["name" : "Australian", "code": "australian"]]
        categories += [["name" : "Austrian", "code": "austrian"]]
        categories += [["name" : "Baguettes", "code": "baguettes"]]
        categories += [["name" : "Bangladeshi", "code": "bangladeshi"]]
        categories += [["name" : "Barbeque", "code": "bbq"]]
        categories += [["name" : "Basque", "code": "basque"]]
        categories += [["name" : "Bavarian", "code": "bavarian"]]
        categories += [["name" : "Beer Garden", "code": "beergarden"]]
        categories += [["name" : "Beer Hall", "code": "beerhall"]]
        categories += [["name" : "Beisl", "code": "beisl"]]
        categories += [["name" : "Belgian", "code": "belgian"]]
        categories += [["name" : "Bistros", "code": "bistros"]]
        categories += [["name" : "Black Sea", "code": "blacksea"]]
        categories += [["name" : "Brasseries", "code": "brasseries"]]
        categories += [["name" : "Brazilian", "code": "brazilian"]]
        categories += [["name" : "Breakfast & Brunch", "code": "breakfast_brunch"]]
        categories += [["name" : "British", "code": "british"]]
        categories += [["name" : "Buffets", "code": "buffets"]]
        categories += [["name" : "Bulgarian", "code": "bulgarian"]]
        categories += [["name" : "Burgers", "code": "burgers"]]
        categories += [["name" : "Burmese", "code": "burmese"]]
        categories += [["name" : "Cafes", "code": "cafes"]]
        categories += [["name" : "Cafeteria", "code": "cafeteria"]]
        categories += [["name" : "Cajun/Creole", "code": "cajun"]]
        categories += [["name" : "Cambodian", "code": "cambodian"]]
        categories += [["name" : "Canadian", "code": "New)"]]
        categories += [["name" : "Canteen", "code": "canteen"]]
        categories += [["name" : "Caribbean", "code": "caribbean"]]
        categories += [["name" : "Catalan", "code": "catalan"]]
        categories += [["name" : "Chech", "code": "chech"]]
        categories += [["name" : "Cheesesteaks", "code": "cheesesteaks"]]
        categories += [["name" : "Chicken Shop", "code": "chickenshop"]]
        categories += [["name" : "Chicken Wings", "code": "chicken_wings"]]
        categories += [["name" : "Chilean", "code": "chilean"]]
        categories += [["name" : "Chinese", "code": "chinese"]]
        categories += [["name" : "Comfort Food", "code": "comfortfood"]]
        categories += [["name" : "Corsican", "code": "corsican"]]
        categories += [["name" : "Creperies", "code": "creperies"]]
        categories += [["name" : "Cuban", "code": "cuban"]]
        categories += [["name" : "Curry Sausage", "code": "currysausage"]]
        categories += [["name" : "Cypriot", "code": "cypriot"]]
        categories += [["name" : "Czech", "code": "czech"]]
        categories += [["name" : "Czech/Slovakian", "code": "czechslovakian"]]
        categories += [["name" : "Danish", "code": "danish"]]
        categories += [["name" : "Delis", "code": "delis"]]
        categories += [["name" : "Diners", "code": "diners"]]
        categories += [["name" : "Dumplings", "code": "dumplings"]]
        categories += [["name" : "Eastern European", "code": "eastern_european"]]
        categories += [["name" : "Ethiopian", "code": "ethiopian"]]
        categories += [["name" : "Fast Food", "code": "hotdogs"]]
        categories += [["name" : "Filipino", "code": "filipino"]]
        categories += [["name" : "Fish & Chips", "code": "fishnchips"]]
        categories += [["name" : "Fondue", "code": "fondue"]]
        categories += [["name" : "Food Court", "code": "food_court"]]
        categories += [["name" : "Food Stands", "code": "foodstands"]]
        categories += [["name" : "French", "code": "french"]]
        categories += [["name" : "French Southwest", "code": "sud_ouest"]]
        categories += [["name" : "Galician", "code": "galician"]]
        categories += [["name" : "Gastropubs", "code": "gastropubs"]]
        categories += [["name" : "Georgian", "code": "georgian"]]
        categories += [["name" : "German", "code": "german"]]
        categories += [["name" : "Giblets", "code": "giblets"]]
        categories += [["name" : "Gluten-Free", "code": "gluten_free"]]
        categories += [["name" : "Greek", "code": "greek"]]
        categories += [["name" : "Halal", "code": "halal"]]
        categories += [["name" : "Hawaiian", "code": "hawaiian"]]
        categories += [["name" : "Heuriger", "code": "heuriger"]]
        categories += [["name" : "Himalayan/Nepalese", "code": "himalayan"]]
        categories += [["name" : "Hong Kong Style Cafe", "code": "hkcafe"]]
        categories += [["name" : "Hot Dogs", "code": "hotdog"]]
        categories += [["name" : "Hot Pot", "code": "hotpot"]]
        categories += [["name" : "Hungarian", "code": "hungarian"]]
        categories += [["name" : "Iberian", "code": "iberian"]]
        categories += [["name" : "Indian", "code": "indpak"]]
        categories += [["name" : "Indonesian", "code": "indonesian"]]
        categories += [["name" : "International", "code": "international"]]
        categories += [["name" : "Irish", "code": "irish"]]
        categories += [["name" : "Island Pub", "code": "island_pub"]]
        categories += [["name" : "Israeli", "code": "israeli"]]
        categories += [["name" : "Italian", "code": "italian"]]
        categories += [["name" : "Japanese", "code": "japanese"]]
        categories += [["name" : "Jewish", "code": "jewish"]]
        categories += [["name" : "Kebab", "code": "kebab"]]
        categories += [["name" : "Korean", "code": "korean"]]
        categories += [["name" : "Kosher", "code": "kosher"]]
        categories += [["name" : "Kurdish", "code": "kurdish"]]
        categories += [["name" : "Laos", "code": "laos"]]
        categories += [["name" : "Laotian", "code": "laotian"]]
        categories += [["name" : "Latin American", "code": "latin"]]
        categories += [["name" : "Live/Raw Food", "code": "raw_food"]]
        categories += [["name" : "Lyonnais", "code": "lyonnais"]]
        categories += [["name" : "Malaysian", "code": "malaysian"]]
        categories += [["name" : "Meatballs", "code": "meatballs"]]
        categories += [["name" : "Mediterranean", "code": "mediterranean"]]
        categories += [["name" : "Mexican", "code": "mexican"]]
        categories += [["name" : "Middle Eastern", "code": "mideastern"]]
        categories += [["name" : "Milk Bars", "code": "milkbars"]]
        categories += [["name" : "Modern Australian", "code": "modern_australian"]]
        categories += [["name" : "Modern European", "code": "modern_european"]]
        categories += [["name" : "Mongolian", "code": "mongolian"]]
        categories += [["name" : "Moroccan", "code": "moroccan"]]
        categories += [["name" : "New Zealand", "code": "newzealand"]]
        categories += [["name" : "Night Food", "code": "nightfood"]]
        categories += [["name" : "Norcinerie", "code": "norcinerie"]]
        categories += [["name" : "Open Sandwiches", "code": "opensandwiches"]]
        categories += [["name" : "Oriental", "code": "oriental"]]
        categories += [["name" : "Pakistani", "code": "pakistani"]]
        categories += [["name" : "Parent Cafes", "code": "eltern_cafes"]]
        categories += [["name" : "Parma", "code": "parma"]]
        categories += [["name" : "Persian/Iranian", "code": "persian"]]
        categories += [["name" : "Peruvian", "code": "peruvian"]]
        categories += [["name" : "Pita", "code": "pita"]]
        categories += [["name" : "Pizza", "code": "pizza"]]
        categories += [["name" : "Polish", "code": "polish"]]
        categories += [["name" : "Portuguese", "code": "portuguese"]]
        categories += [["name" : "Potatoes", "code": "potatoes"]]
        categories += [["name" : "Poutineries", "code": "poutineries"]]
        categories += [["name" : "Pub Food", "code": "pubfood"]]
        categories += [["name" : "Rice", "code": "riceshop"]]
        categories += [["name" : "Romanian", "code": "romanian"]]
        categories += [["name" : "Rotisserie Chicken", "code": "rotisserie_chicken"]]
        categories += [["name" : "Rumanian", "code": "rumanian"]]
        categories += [["name" : "Russian", "code": "russian"]]
        categories += [["name" : "Salad", "code": "salad"]]
        categories += [["name" : "Sandwiches", "code": "sandwiches"]]
        categories += [["name" : "Scandinavian", "code": "scandinavian"]]
        categories += [["name" : "Scottish", "code": "scottish"]]
        categories += [["name" : "Seafood", "code": "seafood"]]
        categories += [["name" : "Serbo Croatian", "code": "serbocroatian"]]
        categories += [["name" : "Signature Cuisine", "code": "signature_cuisine"]]
        categories += [["name" : "Singaporean", "code": "singaporean"]]
        categories += [["name" : "Slovakian", "code": "slovakian"]]
        categories += [["name" : "Soul Food", "code": "soulfood"]]
        categories += [["name" : "Soup", "code": "soup"]]
        categories += [["name" : "Southern", "code": "southern"]]
        categories += [["name" : "Spanish", "code": "spanish"]]
        categories += [["name" : "Steakhouses", "code": "steak"]]
        categories += [["name" : "Sushi Bars", "code": "sushi"]]
        categories += [["name" : "Swabian", "code": "swabian"]]
        categories += [["name" : "Swedish", "code": "swedish"]]
        categories += [["name" : "Swiss Food", "code": "swissfood"]]
        categories += [["name" : "Tabernas", "code": "tabernas"]]
        categories += [["name" : "Taiwanese", "code": "taiwanese"]]
        categories += [["name" : "Tapas Bars", "code": "tapas"]]
        categories += [["name" : "Tapas/Small Plates", "code": "tapasmallplates"]]
        categories += [["name" : "Tex-Mex", "code": "tex-mex"]]
        categories += [["name" : "Thai", "code": "thai"]]
        categories += [["name" : "Traditional Norwegian", "code": "norwegian"]]
        categories += [["name" : "Traditional Swedish", "code": "traditional_swedish"]]
        categories += [["name" : "Trattorie", "code": "trattorie"]]
        categories += [["name" : "Turkish", "code": "turkish"]]
        categories += [["name" : "Ukrainian", "code": "ukrainian"]]
        categories += [["name" : "Uzbek", "code": "uzbek"]]
        categories += [["name" : "Vegan", "code": "vegan"]]
        categories += [["name" : "Vegetarian", "code": "vegetarian"]]
        categories += [["name" : "Venison", "code": "venison"]]
        categories += [["name" : "Vietnamese", "code": "vietnamese"]]
        categories += [["name" : "Wok", "code": "wok"]]
        categories += [["name" : "Wraps", "code": "wraps"]]
        categories += [["name" : "Yugoslav", "code": "yugoslav"]]

    }
    func getData() -> [Dictionary<String, String>] {
        return categories
    }
    func getCodeAsArray() -> [String] {
        var ret = [String]()
        for item in categories {
            if let code = item["code"]{
                ret += [code]
            }
        }
        return ret
    }
    func codeFromName(name: String) -> String {
        var ret = ""
        if name == "All" { //skip All
            return ret
        }
        for item in categories {
            if let nameTmp = item["name"]{
                if nameTmp == name {
                    return item["code"]!
                }
            }
        }
        return ret

    }
}